# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alvaro/Vision/Programas/Practica1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alvaro/Vision/Programas/Practica1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alvaro/Vision/Programas/Practica1/CMakeFiles /home/alvaro/Vision/Programas/Practica1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alvaro/Vision/Programas/Practica1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named contraste

# Build rule for target.
contraste: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 contraste
.PHONY : contraste

# fast build rule for target.
contraste/fast:
	$(MAKE) -f CMakeFiles/contraste.dir/build.make CMakeFiles/contraste.dir/build
.PHONY : contraste/fast

#=============================================================================
# Target rules for targets named hist

# Build rule for target.
hist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hist
.PHONY : hist

# fast build rule for target.
hist/fast:
	$(MAKE) -f CMakeFiles/hist.dir/build.make CMakeFiles/hist.dir/build
.PHONY : hist/fast

#=============================================================================
# Target rules for targets named alien

# Build rule for target.
alien: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 alien
.PHONY : alien

# fast build rule for target.
alien/fast:
	$(MAKE) -f CMakeFiles/alien.dir/build.make CMakeFiles/alien.dir/build
.PHONY : alien/fast

#=============================================================================
# Target rules for targets named distortion

# Build rule for target.
distortion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 distortion
.PHONY : distortion

# fast build rule for target.
distortion/fast:
	$(MAKE) -f CMakeFiles/distortion.dir/build.make CMakeFiles/distortion.dir/build
.PHONY : distortion/fast

#=============================================================================
# Target rules for targets named reduce_colors

# Build rule for target.
reduce_colors: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reduce_colors
.PHONY : reduce_colors

# fast build rule for target.
reduce_colors/fast:
	$(MAKE) -f CMakeFiles/reduce_colors.dir/build.make CMakeFiles/reduce_colors.dir/build
.PHONY : reduce_colors/fast

alien.o: alien.cpp.o

.PHONY : alien.o

# target to build an object file
alien.cpp.o:
	$(MAKE) -f CMakeFiles/alien.dir/build.make CMakeFiles/alien.dir/alien.cpp.o
.PHONY : alien.cpp.o

alien.i: alien.cpp.i

.PHONY : alien.i

# target to preprocess a source file
alien.cpp.i:
	$(MAKE) -f CMakeFiles/alien.dir/build.make CMakeFiles/alien.dir/alien.cpp.i
.PHONY : alien.cpp.i

alien.s: alien.cpp.s

.PHONY : alien.s

# target to generate assembly for a file
alien.cpp.s:
	$(MAKE) -f CMakeFiles/alien.dir/build.make CMakeFiles/alien.dir/alien.cpp.s
.PHONY : alien.cpp.s

contraste.o: contraste.cpp.o

.PHONY : contraste.o

# target to build an object file
contraste.cpp.o:
	$(MAKE) -f CMakeFiles/contraste.dir/build.make CMakeFiles/contraste.dir/contraste.cpp.o
.PHONY : contraste.cpp.o

contraste.i: contraste.cpp.i

.PHONY : contraste.i

# target to preprocess a source file
contraste.cpp.i:
	$(MAKE) -f CMakeFiles/contraste.dir/build.make CMakeFiles/contraste.dir/contraste.cpp.i
.PHONY : contraste.cpp.i

contraste.s: contraste.cpp.s

.PHONY : contraste.s

# target to generate assembly for a file
contraste.cpp.s:
	$(MAKE) -f CMakeFiles/contraste.dir/build.make CMakeFiles/contraste.dir/contraste.cpp.s
.PHONY : contraste.cpp.s

distortion.o: distortion.cpp.o

.PHONY : distortion.o

# target to build an object file
distortion.cpp.o:
	$(MAKE) -f CMakeFiles/distortion.dir/build.make CMakeFiles/distortion.dir/distortion.cpp.o
.PHONY : distortion.cpp.o

distortion.i: distortion.cpp.i

.PHONY : distortion.i

# target to preprocess a source file
distortion.cpp.i:
	$(MAKE) -f CMakeFiles/distortion.dir/build.make CMakeFiles/distortion.dir/distortion.cpp.i
.PHONY : distortion.cpp.i

distortion.s: distortion.cpp.s

.PHONY : distortion.s

# target to generate assembly for a file
distortion.cpp.s:
	$(MAKE) -f CMakeFiles/distortion.dir/build.make CMakeFiles/distortion.dir/distortion.cpp.s
.PHONY : distortion.cpp.s

hist.o: hist.cpp.o

.PHONY : hist.o

# target to build an object file
hist.cpp.o:
	$(MAKE) -f CMakeFiles/hist.dir/build.make CMakeFiles/hist.dir/hist.cpp.o
.PHONY : hist.cpp.o

hist.i: hist.cpp.i

.PHONY : hist.i

# target to preprocess a source file
hist.cpp.i:
	$(MAKE) -f CMakeFiles/hist.dir/build.make CMakeFiles/hist.dir/hist.cpp.i
.PHONY : hist.cpp.i

hist.s: hist.cpp.s

.PHONY : hist.s

# target to generate assembly for a file
hist.cpp.s:
	$(MAKE) -f CMakeFiles/hist.dir/build.make CMakeFiles/hist.dir/hist.cpp.s
.PHONY : hist.cpp.s

reduce_colors.o: reduce_colors.cpp.o

.PHONY : reduce_colors.o

# target to build an object file
reduce_colors.cpp.o:
	$(MAKE) -f CMakeFiles/reduce_colors.dir/build.make CMakeFiles/reduce_colors.dir/reduce_colors.cpp.o
.PHONY : reduce_colors.cpp.o

reduce_colors.i: reduce_colors.cpp.i

.PHONY : reduce_colors.i

# target to preprocess a source file
reduce_colors.cpp.i:
	$(MAKE) -f CMakeFiles/reduce_colors.dir/build.make CMakeFiles/reduce_colors.dir/reduce_colors.cpp.i
.PHONY : reduce_colors.cpp.i

reduce_colors.s: reduce_colors.cpp.s

.PHONY : reduce_colors.s

# target to generate assembly for a file
reduce_colors.cpp.s:
	$(MAKE) -f CMakeFiles/reduce_colors.dir/build.make CMakeFiles/reduce_colors.dir/reduce_colors.cpp.s
.PHONY : reduce_colors.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... contraste"
	@echo "... rebuild_cache"
	@echo "... hist"
	@echo "... alien"
	@echo "... distortion"
	@echo "... reduce_colors"
	@echo "... alien.o"
	@echo "... alien.i"
	@echo "... alien.s"
	@echo "... contraste.o"
	@echo "... contraste.i"
	@echo "... contraste.s"
	@echo "... distortion.o"
	@echo "... distortion.i"
	@echo "... distortion.s"
	@echo "... hist.o"
	@echo "... hist.i"
	@echo "... hist.s"
	@echo "... reduce_colors.o"
	@echo "... reduce_colors.i"
	@echo "... reduce_colors.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

